### ISSUE TITLE
Create Cloud Foundry metadata files

### ISSUE THREAD

**Issue by faberald** [Inventory-Squad/inventory#109]
**As a** developer
**I need** to add cloud foundry metadata files 
**So that** IBM cloud can know how to deploy the project.

**Assumptions:** 
* Using IBM cloud.

**Acceptance Criteria:**
```
Given IBM cloud service and cloud foundry metadata files, 
When I use IBM cloud service to deploy the project
Then the deployment is successful.
```

**Comment by eatingzhang0611** [comment]
Metadata files should include:
1. manifest.yml, 
2. Procfile
3. runtime.txt
