### ISSUE TITLE
Connect CD pipeline to GitHub repo

### ISSUE THREAD

**Issue by faberald** [Inventory-Squad/inventory#116]
**As a** developer
**I need** to use CD pipeline 
**So that** we can  protect our repo 

**Assumptions:** 
* Using IBM Cloud
* Using Github
* Using Delivery Pipeline toolchain

**Acceptance Criteria:**
```
Given a cloud foundry app
When I use CD pipeline
Then I can build and deploy the project when the master branch changes. 
```

**Comment by SonakshiRaizada** [comment]
Need permission from project owner to setup webhook
