### ISSUE TITLE
Decide which database to use

### ISSUE THREAD

**Issue by eatingzhang0611** [Inventory-Squad/inventory#13]
**As a** developer
**I need** a database to store our data
**So that** inventory data can be stored, managed and analyzed uniformly.

**Assumptions:** 
* Product data use the same field names.

**Acceptance Criteria:**
```
Given I am a developer,
When I query, create, delete or update an entry in the database
Then the database should be able to reflect the change correctly.
```

**Comment by eatingzhang0611** [comment]
The homework does not seem to have any requirement about which kind of database we should use.
I have course project experience in both SQL and NoSQL, so I am open to both. Personally, I would choose a relational database for this project, such as MySQL. Since I don't have much work experience, I am also wondering which kind of solution would be used in a real commercial product.

**Comment by joanne3634** [comment]
Decide to use MySQL
