### ISSUE TITLE
Write behave tests for querying an inventory by a given attribute

### ISSUE THREAD

**Issue by SonakshiRaizada** [Inventory-Squad/inventory#134]
**As a** developer
**I need** test cases in feature and steps 
**So that** querying an inventory by a given attribute can pass the behave test.

**Assumptions:** 
* Using Gherkin syntax 
* Using behave tool 
* Using Selenium for UI testing

**Acceptance Criteria:**
```
Given one or more attribute value,
When I fill the fields with those value,
And I press the search button,
Then I can see fields with correct information. 
```

**Comment by eatingzhang0611** [comment]
May need to split this issue to several smaller ones since we wrote different functions for each search.
