### ISSUE TITLE
Standardize error message

### ISSUE THREAD

**Issue by faberald** [Inventory-Squad/inventory#161]
**As a** developer
**I need** standard error message 
**So that** I will not receive 500 errors when I throw bad data to the service

**Assumptions:** 

Code already refactor (by Flask-RESTPlus)

**Acceptance Criteria:**
```
Given the Flask-RESTPlus code
When I throw bad data to the service
Then I will not receive any 500 errors 
```

**Comment by eatingzhang0611** [comment]
From Assignment requirement 4:
> I will throw bad data at your service and I expect to not see 500 errors. ;-)

**Comment by faberald** [comment]
**Things need to discuss:**
```
1. Is GET /inventory?condition a valid query
2. Is GET /inventory?restock=true&condition=new a valid query
3. Is GET /inventory?invalidparameter=1&product-id=1 a valid query
```
`What is the flash message when DELETE an inventory with inventory id as null or empty`
